/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Frame7554OverridesProps = {
    "18"?: PrimitiveOverrideProps<TextProps>;
    Frame7554?: PrimitiveOverrideProps<ViewProps>;
    "Frame 755329584"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 62"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 63"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 64"?: PrimitiveOverrideProps<ViewProps>;
    "Charging Stations29317"?: PrimitiveOverrideProps<TextProps>;
    "Charging Stations29318"?: PrimitiveOverrideProps<TextProps>;
    Vector28736?: PrimitiveOverrideProps<IconProps>;
    Vector28737?: PrimitiveOverrideProps<IconProps>;
    Vector28738?: PrimitiveOverrideProps<IconProps>;
    "MicrosoftTeams-image (12) 2"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 66"?: PrimitiveOverrideProps<ViewProps>;
    "Group 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector28742?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 65"?: PrimitiveOverrideProps<ViewProps>;
    English?: PrimitiveOverrideProps<TextProps>;
    Vector28748?: PrimitiveOverrideProps<IconProps>;
    "Group 348"?: PrimitiveOverrideProps<ViewProps>;
    Vector28751?: PrimitiveOverrideProps<IconProps>;
    Vector28752?: PrimitiveOverrideProps<IconProps>;
    Vector28753?: PrimitiveOverrideProps<IconProps>;
    Vector28754?: PrimitiveOverrideProps<IconProps>;
    DASHBOARD?: PrimitiveOverrideProps<TextProps>;
    "CHARGING STATION"?: PrimitiveOverrideProps<TextProps>;
    Vector28758?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 67"?: PrimitiveOverrideProps<ViewProps>;
    "Charging Stations currently with faults or connectivity less"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 69"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 70"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 71"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 7552"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 6828760"?: PrimitiveOverrideProps<ViewProps>;
    "Avatar Unit"?: PrimitiveOverrideProps<ViewProps>;
    "Group 345"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 140"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 141"?: PrimitiveOverrideProps<IconProps>;
    "Frame 7550"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 7551"?: PrimitiveOverrideProps<FlexProps>;
    "in total"?: PrimitiveOverrideProps<TextProps>;
    "Occupied EVSE"?: PrimitiveOverrideProps<TextProps>;
    "0293134"?: PrimitiveOverrideProps<TextProps>;
    "Group 346"?: PrimitiveOverrideProps<ViewProps>;
    Vector29588?: PrimitiveOverrideProps<IconProps>;
    Text?: PrimitiveOverrideProps<TextProps>;
    Dashboard?: PrimitiveOverrideProps<TextProps>;
    "Information on Infrastructure & Charging Process"?: PrimitiveOverrideProps<TextProps>;
    "Faults and Connectivity Loss"?: PrimitiveOverrideProps<TextProps>;
    "1 out of 10"?: PrimitiveOverrideProps<TextProps>;
    "Charging Station Groups"?: PrimitiveOverrideProps<TextProps>;
    Locations29320?: PrimitiveOverrideProps<TextProps>;
    Locations29321?: PrimitiveOverrideProps<TextProps>;
    Models?: PrimitiveOverrideProps<TextProps>;
    "CHARGING SESSIONS"?: PrimitiveOverrideProps<TextProps>;
    Vector29327?: PrimitiveOverrideProps<IconProps>;
    Vector29329?: PrimitiveOverrideProps<IconProps>;
    Vector29330?: PrimitiveOverrideProps<IconProps>;
    Vector29331?: PrimitiveOverrideProps<IconProps>;
    CUSTOMERS?: PrimitiveOverrideProps<TextProps>;
    "ADMIN & CONFIG"?: PrimitiveOverrideProps<TextProps>;
    "SETTINGS & HELP"?: PrimitiveOverrideProps<TextProps>;
    "location-filled_svgrepo.com"?: PrimitiveOverrideProps<ViewProps>;
    "Location-Filled"?: PrimitiveOverrideProps<ViewProps>;
    Vector29348?: PrimitiveOverrideProps<IconProps>;
    "Group 347"?: PrimitiveOverrideProps<ViewProps>;
    "Page-1"?: PrimitiveOverrideProps<ViewProps>;
    add?: PrimitiveOverrideProps<ViewProps>;
    "Combined-Shape"?: PrimitiveOverrideProps<IconProps>;
    "Group 350"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 72295107"?: PrimitiveOverrideProps<ViewProps>;
    "Go to issues295109"?: PrimitiveOverrideProps<TextProps>;
    "Group 351"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 72295124"?: PrimitiveOverrideProps<ViewProps>;
    "Go to issues295125"?: PrimitiveOverrideProps<TextProps>;
    "Group 352"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 72295137"?: PrimitiveOverrideProps<ViewProps>;
    "Go to issues295138"?: PrimitiveOverrideProps<TextProps>;
    "Group 349"?: PrimitiveOverrideProps<ViewProps>;
    Vector295115?: PrimitiveOverrideProps<IconProps>;
    Vector295116?: PrimitiveOverrideProps<IconProps>;
    Vector295117?: PrimitiveOverrideProps<IconProps>;
    "Rejected and Time out Charging Sessions"?: PrimitiveOverrideProps<TextProps>;
    "0293121"?: PrimitiveOverrideProps<TextProps>;
    "0293123"?: PrimitiveOverrideProps<TextProps>;
    "Charging Sessions currently running at your stations"?: PrimitiveOverrideProps<TextProps>;
    "Active Charging Sessions"?: PrimitiveOverrideProps<TextProps>;
    "Total Consumed Energy"?: PrimitiveOverrideProps<TextProps>;
    "7.485 kWh"?: PrimitiveOverrideProps<TextProps>;
    Vector293119?: PrimitiveOverrideProps<IconProps>;
    Vector295121?: PrimitiveOverrideProps<IconProps>;
    Vector29350?: PrimitiveOverrideProps<IconProps>;
    "Sessions within the last 7 days"?: PrimitiveOverrideProps<TextProps>;
    "within the past 7 days"?: PrimitiveOverrideProps<TextProps>;
    "Line 1"?: PrimitiveOverrideProps<IconProps>;
    "Line 2"?: PrimitiveOverrideProps<IconProps>;
    "Line 3"?: PrimitiveOverrideProps<IconProps>;
    "Line 4"?: PrimitiveOverrideProps<IconProps>;
    "Frame 7553295126"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 68295127"?: PrimitiveOverrideProps<ViewProps>;
    "Overview of all Charging Stations"?: PrimitiveOverrideProps<TextProps>;
    "Within the overview you see all charging stations that are registered within your account. You can use the description to identify the different status within your charging station."?: PrimitiveOverrideProps<TextProps>;
    "tag_svgrepo.com"?: PrimitiveOverrideProps<ViewProps>;
    Vector29339?: PrimitiveOverrideProps<IconProps>;
    "charging-pile_svgrepo.com"?: PrimitiveOverrideProps<ViewProps>;
    "\u9875\u9762-1"?: PrimitiveOverrideProps<ViewProps>;
    Transport?: PrimitiveOverrideProps<ViewProps>;
    charging_pilen_fill?: PrimitiveOverrideProps<ViewProps>;
    MingCute?: PrimitiveOverrideProps<IconProps>;
    "\u5F62\u72B6"?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type Frame7554Props = React.PropsWithChildren<Partial<ViewProps> & {
    property1?: "Default" | "Variant2";
} & {
    overrides?: Frame7554OverridesProps | undefined | null;
}>;
export default function Frame7554(props: Frame7554Props): React.ReactElement;
